data_local: tmp/
data_remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
tokenizer_name: gpt2
max_seq_len: 2048
global_seed: 17

# Run Name
run_name: 1b-inference-test
name: mosaic_gpt

# Model
model:
  name: mosaic_gpt
  init_device: meta
  tokenizer_name: gpt2
  d_model: 2048
  n_heads: 16 # Modified 24->16 so that d_head == 128 to satisfy FlashAttention
  n_layers: 24
  mlp_ratio: 4
  max_seq_len: 2048
  vocab_size: 50368
  init_std: 0.02
  attn_pdrop: 0.0
  resid_pdrop: 0.0
  emb_pdrop: 0.0
  attn_impl: triton 
  low_precision_layernorm: true
  attn_clip_qkv: 2.0
  bias: true

# Tokenizer
tokenizer:
    name: gpt2
    kwargs:
        model_max_length: 2048

# Dataloaders
train_loader:
  name: text
  dataset:
    local: tmp/
    remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
    split: train
    shuffle: true
    tokenizer_name: gpt2
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: tmp/
    remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
    split: val
    shuffle: false
    tokenizer_name: gpt2
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 0.1dur
  alpha_f: 0.01

optimizer:
  name: decoupled_lionw
  lr: 3.2e-4
  betas:
    - 0.9
    - 0.95
  weight_decay: 3.2e-5

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 12400ba # ~ 26B tokens
eval_interval: 500ba
eval_subset_num_batches: -1
eval_first: true
global_train_batch_size: 1024 # ~ 2M tokens

# System
seed: 17
device_eval_batch_size: 4
device_train_microbatch_size: 4
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_cpu_offload: false
  verbose: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 50ba

callbacks:
  speed_monitor:
    window_size: 10
  runtime_estimator: {}
  lr_monitor: {}
  memory_monitor: {}
  optimizer_monitor: {}
  health_checker:
    test_mode: true

loggers:
  wandb: {}

# Inference config
benchmark_name: 1b
use_quantized_model: true
quantized_path: checkpoints/quantized/1b.pt

save_interval: 500ba
save_folder: local/folder
load_path: checkpoints/adjusted/1b-checkpoint.pt
save_num_checkpoints_to_keep: 1
autoresume: true
