data_local: tmp/
data_remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
tokenizer_name: gpt2
max_seq_len: 2048
global_seed: 17

# Run Name
run_name: inference-test-30b
name: mosaic_gpt

# Model
model:
  name: mosaic_gpt
  init_device: meta
  tokenizer_name: gpt2
  d_model: 7168
  n_heads: 56
  n_layers: 48
  mlp_ratio: 4
  max_seq_len: 2048
  vocab_size: 50368
  attn_impl: triton

# Tokenizer
tokenizer:
    name: gpt2
    kwargs:
        model_max_length: 2048

# Dataloaders
train_loader:
  name: text
  dataset:
    local: tmp/
    remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
    split: train
    shuffle: true
    tokenizer_name: gpt2
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: tmp/
    remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
    split: val
    shuffle: false
    tokenizer_name: gpt2
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 1.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 143100ba # ~ 600B tokens
eval_interval: 10000ba
eval_subset_num_batches: -1
global_train_batch_size: 1024

# System
seed: ${global_seed}
device_eval_batch_size: 8
device_train_microbatch_size: 8
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_cpu_offload: false
  verbose: true
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  runtime_estimator: {}
  lr_monitor: {}
  memory_monitor: {}
  optimizer_monitor: {}
  health_checker:
    test_mode: true

loggers:
  wandb: {}

# Quantized model
benchmark_name: 30b
use_quantized_model: true
quantized_path: checkpoints/quantized/30b.pt

save_interval: 1000ba
save_folder: local/folder
load_path: checkpoints/30b-checkpoint.pt
save_num_checkpoints_to_keep: 1
autoresume: true
